name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y:%m:%d:%H:%M" | sed 's/\(....:..:..:..:.\)./\10/')"
      shell: bash
    
    #- uses: actions/checkout@v2
    - name: Check NPM Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.npm
        key: npm-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
         npm-  
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm test
      env:
        CI: true
